
version: 2

models:
    - name: fact_sales
      tests:
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 2
            group_by: [transaction_date]
      columns:
          - name: sale_id
            tests:
              - dbt_expectations.expect_column_values_to_not_be_null
              - dbt_expectations.expect_column_values_to_be_unique
          - name: unit_amount
            tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 1  
                max_value: 10
                strictly: false
sources:
  - name: TPCH_SF1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: ORDERS
      - name: CUSTOMER
      - name: NATION
  - name: sales
    schema: dbt_dev
    database: ANALYTICS
    tables:
      - name: src_sales
      - name: fact_sales
